# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

if [ "$TERM" = "xterm-256color" ]; then
echo "                       --------------------------- "
echo "                      | Hi  :>                    |"
echo "                      | Do your great job with me!|"
echo "                       ----------------    ------- "
echo "                                       \  /        "
echo "                                        \/         "
echo "   ======================================          "
echo "  /            \             /           \         "
echo " /              \           /             \        "
echo "|                \         /               |       "
echo "|         _       \_______/       _        |       "
echo "|        |_|                     |_|       |       "
echo "|                                          |       "
echo "|   //////      -------------      //////  |       "
echo "|              /             \             |       "
echo "|             |_______________|            |       "
echo "|              \             /             |       "
echo "|               \___________/              |       "
echo "\                                          /       "
echo " \                 ______                 /        "
echo "  \                                      /         "
echo "   =====================================           "
fi

